kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: crossplane-patches-rbac
subjects:
  - kind: ServiceAccount
    name: default
    namespace: crossplane-system # namespace:operator
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io