---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


helmGlobals:
  chartHome: ./

helmCharts:
- name: cluster-role
  valuesFile: values.yaml

- name: prerequsite-networks
  valuesFile: values.yaml
  
#- name: rosa
#  valuesFile: values.yaml
#
#- name: account-role
#  valuesFile: values.yaml
#  

patches: []   