apiVersion: redhatcop.redhat.io/v1alpha1
kind: Patch
metadata:
  name: cluster-subnet
spec:
  patches:
    cluster-subnet:
      patchTemplate: |
        spec:
           subnets:
             - {{ (lookup "ec2.aws.upbound.io/v1beta1" "Subnet" "" "crossx-public-subnet").status.atProvider.id }}
             - {{ (lookup "ec2.aws.upbound.io/v1beta1" "Subnet" "" "crossx-private-subnet").status.atProvider.id }}    
      patchType: application/merge-patch+json
      targetObjectRef:
        apiVersion: controlplane.cluster.x-k8s.io/v1beta2
        kind: ROSAControlPlane
        name: crossx-control-plane
        namespace: rosa-hcp-1
  serviceAccountRef:
    name: default