#{{- $rosaOpenshiftVersion := .Values.rosa_openshift_version }}
#{{- $redhatAwsId := .Values.redhat_aws_id }}
---
apiVersion: iam.aws.upbound.io/v1beta1
kind: Role
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "5"
    crossplane.io/external-name: ManagedOpenShift-HCP-ROSA-Installer-Role
  #name: ManagedOpenShift-HCP-ROSA-Installer-Role
  name: managedopenshift-hcp-rosa-installer-role
spec:
  forProvider:
    managedPolicyArns:
       - arn:aws:iam::aws:policy/service-role/ROSAInstallerPolicy
    tags:
      red-hat-managed: "true"
      rosa_hcp_policies: "true"
      rosa_role_type: installer 
      rosa_managed_policies: "true" 
      rosa_openshift_version: "{{ .Values.rosa_openshift_version }}" 
      rosa_role_prefix: ManagedOpenShift
    assumeRolePolicy: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Action": [
              "sts:AssumeRole"
            ],
            "Effect": "Allow",
            "Principal": {
              "AWS": [
                "arn:aws:iam::{{ .Values.redhat_aws_id }}:role/RH-Managed-OpenShift-Installer"
              ]
            }
          }
        ]
      }