---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


helmGlobals:
  chartHome: ../../../charts

helmCharts:
  - name: openshift-management
    releaseName: rosa-hcp
    valuesFile: values.yaml