apiVersion: ec2.aws.upbound.io/v1beta1
kind: InternetGateway
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "5"
  labels:
    crossplane/InternetGateway: {{ .Values.cluster_name }}-internetgateway
  name: {{ .Values.cluster_name }}-internetgateway
spec:
  forProvider:
    tags:
      Name: {{ .Values.cluster_name }}
    region: {{ .Values.region }}
    vpcIdSelector:
      matchLabels:
        crossplane/vpc: {{ .Values.cluster_name }}