---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: EIP
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "5"
  labels:
    crossplane/EIP: {{ .Values.cluster_name }}-EIP
  name: {{ .Values.cluster_name }}-eip
spec:
  forProvider:
    tags:
      Name: {{ .Values.cluster_name }}-EIP
    region: {{ .Values.region }}
    vpc: true
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: NATGateway
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "6"
  labels:
    crossplane/NATGateway: {{ .Values.cluster_name }}-NATGateway
  name:  {{ .Values.cluster_name }}-nat-gateway
spec:
  forProvider:
    allocationIdRef:
      name: {{ .Values.cluster_name }}-eip
    connectivityType: public
    region: {{ .Values.region }}
    subnetIdSelector:
      matchLabels:
        crossplane/subnet: {{ .Values.cluster_name }}-public-subnet
    tags:
      Name: {{ .Values.cluster_name }}-nat-gateway