apiVersion: ec2.aws.upbound.io/v1beta1
kind: Subnet
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "5"
  labels:
    crossplane/subnet: {{ .Values.cluster_name }}-public-subnet
  name: {{ .Values.cluster_name }}-public-subnet
spec:
  forProvider:
    tags:
      Name: {{ .Values.cluster_name }}-public
    availabilityZone: {{ .Values.availabilityZone }}
    cidrBlock: {{ .Values.public_subnet_cidrBlock }}
    region: {{ .Values.region }}
    vpcIdSelector:
      matchLabels:
        crossplane/vpc: {{ .Values.cluster_name }}