---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: RouteTable
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "5"
  labels:
    crossplane/routetable: {{ .Values.cluster_name }}-routetable-private
  name: {{ .Values.cluster_name }}-routetable-private
spec:
  forProvider:
    tags:
      Name: {{ .Values.cluster_name }}-private
    region: {{ .Values.region }}
    vpcIdSelector:
      matchLabels:
        crossplane/vpc: {{ .Values.cluster_name }}
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: RouteTableAssociation
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "6"
  labels:
     crossplane/RouteTableAssociation: {{ .Values.cluster_name }}-RouteTableAssociation-private
  name: {{ .Values.cluster_name }}-routetableassociation-private
spec:
  forProvider:
    region: {{ .Values.region }}
    routeTableIdRef:
      name: {{ .Values.cluster_name }}-routetable-private
    subnetIdRef:
      name: {{ .Values.cluster_name }}-private-subnet
    #gatewayIdRef:
    #  name: {{ .Values.cluster_name }}-internetgateway
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: Route
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "7"
  labels:
     crossplane/Route: {{ .Values.cluster_name }}-Route
  name: {{ .Values.cluster_name }}-route-private
spec:
  forProvider:
    destinationCidrBlock: 0.0.0.0/0
    natGatewayIdRef:
      name: {{ .Values.cluster_name }}-nat-gateway
    region: {{ .Values.region }}
    routeTableIdRef:
      name: {{ .Values.cluster_name }}-routetable-private