apiVersion: ec2.aws.upbound.io/v1beta1
kind: VPC
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  labels:
    crossplane/vpc: {{ .Values.cluster_name }}
  name: {{ .Values.cluster_name }}-vpc
spec:
  forProvider:
    cidrBlock: {{ .Values.vpc_cidrBlock }}
    enableDnsHostnames: true
    enableDnsSupport: true
    region:  {{ .Values.region }}